### ISSUE TITLE
Dataset cards TODO

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#21]
@bswhite, @vpchung - I'm attempting to capture and track issues that need to be cleaned up with datasets annotations and cards. Let me know if there's anything I missed, or if you have thoughts on any of the specific tasks.

![image](https://user-images.githubusercontent.com/5033229/79941641-9bbb1780-8419-11ea-9d88-ec40fbb2ca8d.png)

- [x] Grab dataset "title" from GEO to use for `datasetName` (for any datasets with accession only)
- [x] Finalize link format for `publication`
- [ ] Finalize **PUBLICATION** secondary label link destination (i.e., PubMed vs. filtered Explore/Publications page)
- [x] Replace all `"Not Applicable"`, `"NA"`, or `"None"` values with actual `NA`s
- [x] Finalize link format for `externalLink`
- [x] Fix/translate unicode characters in `overallDesign`
- [x] Finalize secondary label for grants (i.e., **GRANT NAME** vs. **GRANT**)
\>> use **GRANT NAME**

_Optional:_
- [ ] Add `synapseLocation`
- [ ] Grab dataset "contributors" from GEO and add as column, secondary label (or subtitle)
