### ISSUE TITLE
Publication cards TODO

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#22]
@bswhite, @vpchung - I'm attempting to capture and track issues that need to be cleaned up with publications annotations and cards. Let me know if there's anything I missed, or if you have thoughts on any of the specific tasks.

![image](https://user-images.githubusercontent.com/5033229/79943408-a8416f00-841d-11ea-931f-2b4dad147f30.png)

- [x] Finalize **DATASET** secondary label link destination (i.e., Explore/Datasets/DetailsPage vs. filtered Explore/Datasets page)
\>> use Explore/Datasets/DetailsPage
- [x] Finalize secondary label for datasets (i.e., **DATASET** vs. **DATASETS**)
\>> use **DATASETS**
- [x] Replace all `"Not Applicable"`, `"NA"`, or `"None"` values with actual `NA`s
- [x] Fix extra leading space bug with dataset links (e.g., `"datasetAlias=%20SRP081644"`)
- [x] Fix extra leading space bug with grant links (e.g., `"grantName=%20Center%20on%20the%20Physics%20of%20Cancer%20Metabolism"`)
- [x] Finalize secondary label for grants (i.e., **GRANT NAME** vs. **GRANT**)
\>> use **GRANT NAME**
- [ ] Figure out how to handle `grantName` values with commas (e.g., `"Systems approaches to understanding the relationships between genotype, signaling, and therapeutic efficacy"`)
- [ ] Handle encoding of special characters for URLs (e.g., `"Intratumor heterogeneity underlying treatment resistance in HER2+ breast tumors"`, where `"+"` becomes `"%2B"`)

_Optional:_
- [x] Add `tool` or `tools` column and secondary label with link(s) to portal tool entities (Explore/Tools/DetailsPage or filtered Explore/Tools page)
- [x] Finalize title link destination (i.e., PubMed vs. Explore/Publications/DetailsPage)
- [x] Add separate `pubMedLink` secondary label (if title link destination is changed)

**Comment by bswhite** [comment]
In order of your above tasks:
1. I like the dataset link going to a details page. This lets the user see and download the files. And maybe eventually will provide additional information. Bringing them to a dataset card probably won't provide that much more information than is on the pub card.
2. I have a slight preference for datasets (plural) over dataset; the former seems more general.
3. Note that blanks (and possibly NAs?) are not rendered. Sometimes it feels (i.e., I can't tell you exactly when) that we want "Not Applicable" over blank. I guess blank implies not provided, to me, whereas Not Applicable is a very intentional -- "this does not apply." And I prefer "Not Applicable" over NA/NULL/etc.
5. I prefer "Grant Name" over "Grant." On the card (your snapshot), I don't have a preference. But when it appears as a search field, "Grant" would be ambiguous -- e.g., can I search for a grant number? Or a grant name? I prefer that facets/fields we search on to leave no ambiguity. e.g., not "Name" but "Grant Name" (did you already fix this?). In Duminda's demo, I've seen people try to search for a person's name in "Name", whereas it was referring to "Grant Name."

Optional:
1. Yes, we should add a tools link (I prefer plural again). And, again, I think it should go to a details page.
2. I prefer title going to details page for several reasons: (1) Most importantly, I want to embed more information on the details page, like the datasets and tools cards (not just links, as here). This again gives us flexibility to add other metadata. (2) It seems jarring to click on a title and be sent off the portal. I prefer such external links to be explicit (as you've done for GEO/dataset links).
3. Yes, I agree we should have a separate pubMedLink. But I would just call it externalLink (e.g., to allow for biorxiv)

**Comment by jaeddy** [comment]
Thanks, @bswhite! I agree with pretty much all of your points. We're obviously a bit limited in terms of "DetailsPage" links (for the next couple days), but this is probably the direction in which we want to go.

> It seems jarring to click on a <link> and be sent off the portal. I prefer such external links to be explicit (as you've done for GEO/dataset links).

Yes yes yes. 100% agree.

> Note that blanks (and possibly NAs?) are not rendered. Sometimes it feels (i.e., I can't tell you exactly when) that we want "Not Applicable" over blank. I guess blank implies not provided, to me, whereas Not Applicable is a very intentional -- "this does not apply." And I prefer "Not Applicable" over NA/NULL/etc.

I think for the portal, we can generally err on the side of _not_ displaying any missing information (whether it's not applicable or unknown). We should definitely keep "Not Applicable" in our internal annotations/tables, as this is informative for ongoing curation. If you think "Not Applicable" should be included in the portal UI cards/filters, I could be convinced.

**Comment by vpchung** [comment]
Sorry @jaeddy, found a couple more bugs that will need fixing!

As I was reviewing the grants, I also checked to see whether the publication cards would link back to the **Grant Details** page. Similar to the dataset links, there is a leading space in the subsequent grant links when there are more than one listed.

Some grant names have commas in them, e.g. `Systems approaches to understanding the relationships between genotype, signaling, and therapeutic efficacy` which results in three hyperlinks instead of one. That being said, clicking on the first and third hyperlink _does_ link back correctly, but the second ("[signaling](https://staging.csbc-pson.synapse.org/Explore/Grants/DetailsPage?grantName=%20signaling)") does not behave properly -- it shows three grants at the top whereas the "details" portion remains hanging.

And finally, some grant names contain characters that are considered special in URL, e.g. `Intratumor heterogeneity underlying treatment resistance in HER2+ breast tumors`. This, I think, can be easily fixed if we do some encoding first, so that `+` becomes `%2B`.

**Comment by jaeddy** [comment]
Thanks, @vpchung! No need to apologize. Reporting bugs and things that need fixing is exactly the point of this issue!

I'll update the list to include these items.

**Comment by vpchung** [comment]
The remaining item ("Figure out how to handle grantName values with commas") can be solved with either using a different character (semicolon?) or just not using commas at all.  TBD with the data curators.
