### ISSUE TITLE
Tool cards TODO

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#23]
@bswhite, @vpchung - I'm attempting to capture and track issues that need to be cleaned up with tools annotations and cards. Let me know if there's anything I missed, or if you have thoughts on any of the specific tasks.

![image](https://user-images.githubusercontent.com/5033229/79944163-b09aa980-841f-11ea-9689-afd320ce43bd.png)

- [x] Add secondary label (**PUBLICATION**) for `publication` column
- [x] Finalize link format for `publication`
- [x] Finalize **PUBLICATION** secondary label link destination (i.e., PubMed vs. Explore/Publications/DetailsPage vs. filtered Explore/Publications page)
- [x] Replace all `"Not Applicable"`, `"NA"`, or `"None"` values with actual `NA`s
- [x] Finalize secondary label for grants (i.e., **GRANT NAME** vs. **GRANT**)
\>> use **GRANT NAME**
- [ ] Add secondary label (**THEME**) for `theme` column

_Optional:_
- [ ] Grab tool "contributor" from [syn21488853](https://www.synapse.org/#!Synapse:syn21488853/tables/) and add as column, secondary label (or subtitle)

**Comment by vpchung** [comment]
@jaeddy 

>  **Add secondary label (PUBLICATION) for publication column**

Done!  It is formatted as the publication title.

> **Finalize PUBLICATION secondary label link destination (i.e., PubMed vs. Explore/Publications/DetailsPage vs. filtered Explore/Publications page)**

The current destination is to the publication details card.

> **Add secondary label (THEME) for theme column**

The new tools table does not have `theme`, so I opted to include `topic` as a secondary label instead.

Additionally, now that we have more information to display about tools, we could make it so that clicking on a tools card redirects to a details page (much like grants, publications, datasets):

![Screen Shot 2022-02-21 at 8 57 28 PM](https://user-images.githubusercontent.com/9377970/155065972-6a651025-fcf3-497e-8371-a799425e934a.png)

**Comment by jaeddy** [comment]
Awesome, @vpchung! Do these fixes need any additional review/validation, or do you think it's fine to close this issue?

**Comment by vpchung** [comment]
I think we can close this issue now (will do so now)!  Ongoing discussion as to what information to display on the tools card is being tracked in this [JIRA ticket](https://sagebionetworks.jira.com/browse/CPO-10) :)
